### ISSUE TITLE
The generate function returns an integer instead of a string, leading to missing first 0 digits

### ISSUE THREAD

**Issue by eraleis** [jobteaser/erl-otp#1]
## Expected Behavior
When I use `generate/3` to generate a TOTP code with X digits, i want to receive the TOTP code with X digits

## Current Behavior
The `generate` function returns an integer, so if the first digits are `0`, they won't be returned.

## Possible Solution
Returning a string, like in the implementation example from the RFC
```java
public static String generateTOTP(
```

## How to reproduce
```elixir
generate("12345678901234567890", 1567098571, 6) == 56576
```

**Comment by ghost** [comment]
I added two functions to generate the textual representation of a one-time password, with more information in the handbook.
